---
dependencies:
  - { role: cloud_amazon }
  - { role: jetty9_instance, jetty_instance_name: '{{ ice_instance_name }}', jetty_instance_port: '{{ ice_instance_port }}', jetty_jvm_extra_opts: '{{ ice_jvm_extra_opts }}', jetty_jvm_xmx: '{{ ice_jvm_xmx }}' }
