---
# ebs_size:      Size of EBS to create (required)
# ebs_snap:      Snapshot ID to create from (optional)
# ebs_device_id: Device node as host sees it (sd or xvd)

# ebs_volume_id: Returned: ID of new volume (as fact)

# FIXME: can we avoid using facts for this?
# FIXME: maybe parameterize the region/zone one day

- name: Creating new EBS volume (empty)
  command: 'ec2-create-volume --region {{ ansible_ec2_placement_region }} --availability-zone {{ ansible_ec2_placement_availability_zone  }} --size {{ ebs_size }}'
  register: amivol
  when: ebs_snap is not defined or ebs_snap == ''

- name: Creating new EBS volume from snapshot
  command: 'ec2-create-volume --region {{ ansible_ec2_placement_region }} --availability-zone {{ ansible_ec2_placement_availability_zone  }} --size {{ ebs_size }} --snapshot {{ ebs_snap }}'
  register: amivol
  when: ebs_snap is defined and ebs_snap != ''

- name: Saving Volume ID as a fact for later use
  set_fact:
    ebs_volume_id: '{{ item.split("\t")[1] }}'
  with_items: amivol.stdout

- name: Attaching EBS work volume
  command: "ec2-attach-volume --region {{ ansible_ec2_placement_region }} --device {{ ebs_device_id.replace('/dev/xvd', '/dev/sd') }} --instance '{{ ansible_ec2_instance_id }}' '{{ ebs_volume_id }}'"

- name: Waiting for EBS work volume attachment to complete
  wait_for:
    path: '{{ ebs_device_id }}'

