# Don't edit this file, make a local/site.yml instead

# Delete this line when making a local file:
site_defaults: True

# Will try to capture values that may need overriding for a typical local/site.yml file here

# AMI Generation related values:
# For EBS root AMIs:
ami_build_pvm_ebs: True
ami_build_hvm_ebs: True
# For Instance storage root AMIs:
ami_bundle_account: 123456789012
ami_bundle_bucket_path: 'my-amis/buri'
ami_build_pvm_instance: False
ami_build_hvm_instance: False

# Exhibitor related values:
#exhibitor_opts_s3config: 'prefix-exhibitor:config'
#exhibitor_opts_s3region: 'us-east-1'

# Eureka related values:
#eureka_dns_txt_domain: eureka.mydomain.net

# ICE related values:
# S3 info for billing data from AWS
#ice_billing_s3_bucket_names: example-billing
#ice_billing_s3_bucket_prefix: 
# Your company's name
#ice_company_name: Your Company Name
# The S3 bucket Ice can use as it's workspace (needs read and write access)
#ice_work_s3_bucket_name: example-ice-work
# Your AWS Account ID
#ice_account1_aws_id: 123456789011
#ice_admin_password: "mypassword"

# Asgard related value:
#asgard_admin_password: "mypassword"

# Priam related values:
# priam_clustername MUST match the autoscaling group name (before the dash) in order to be used 
# i.e. project_stage_db-useast1 == cluster_name-ec2region
# priam_clustername is effectively the reference to the correct set of SimpleDB Configuration
#priam_clustername: "priam"
#priam_multiregion_enable: false

# This must be set for all multiregion and any single region deployments outside the first three (abc) AZs/datacenters in a region
# i.e. "us-east-1a,us-east-1c,us-west-1a,us-west-1b,us-west-1c" or "us-east-1c,us-east-1d"
# If not set it will not be applied
#priam_zones_available: ""

# If you want backups, set this variable to the name of an s3 bucket you have created.
#priam_s3_bucket: "SET_ME_PLEASE"
#priam_s3_base_dir: "cassandra_backups"

