---
- name: Install build host package dependencies
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - coreutils
    - ec2-ami-tools
    - ec2-api-tools
    - python
    - python-support
    - python-dev
    - python-pip
    - python-jinja2
    - libapt-pkg4.12
    - make
    - qemu-utils
    - git-core
    - openssl

- name: Install boto Python library via pip
  pip: name=boto state=latest

- name: Install AWS CLI via pip
  pip: name=awscli state=latest

- name: Install Ansible via pip
  pip: name=ansible state=latest


