---
# ebs_volume_id:

- name: Identify mount to tear down
  shell: "df | grep {{ ami_device }} | awk '{ print $6 }'"
  register: old_mount
  #ignore_errors: yes

- name: Unmount /proc filesystem from chroot
  command: 'chroot {{ item }} umount /proc'
  with_items: old_mount.stdout
  when: old_mount.stdout != ""

- name: Unmount /dev filesystem from chroot
  command: 'umount {{ item }}/dev'
  with_items: old_mount.stdout
  when: old_mount.stdout != ""

- name: Unmount EBS volume for chroot
  command: 'umount {{ item }}'
  with_items: old_mount.stdout
  when: old_mount.stdout != ""

- name: Discover Volume ID to detatch
  shell: "ec2-describe-instances {{ ansible_ec2_instance_id }} | grep BLOCKDEVICE | grep {{ ami_device.replace('/dev/xvd', '/dev/sd') }}"
  register: ebsvol

- name: Saving Volume ID as a fact for later use
  set_fact:
    ebs_volume_id: '{{ item.split("\t")[2] }}'
  with_items: ebsvol.stdout

- name: Detatch failed working volume
  command: 'ec2-detach-volume --region {{ ansible_ec2_placement_region }} "{{ ebs_volume_id }}"'

- name: Waiting for completion of volume detatch
  command: 'ec2-describe-volumes --region {{ ansible_ec2_placement_region }} "{{ ebs_volume_id }}"'
  register: result
  until: result.stdout.find("ATTACHMENT") == -1
  retries: 30
  delay: 3

- name: Delete EBS working volume
  command: 'ec2-delete-volume --region {{ ansible_ec2_placement_region }} "{{ ebs_volume_id }}"'

