---
- name: Find AKI ID for parent image.
  shell: 'aws ec2 describe-images --region {{ ansible_ec2_placement_region }} --image-ids {{ ami_parent }} --output text | grep ^IMAGES'
  register: aki

- name: Saving AKI ID as a fact for later use
  set_fact:
    ami_aki_id: '{{ item.split("\t")[7] }}'
  with_items: aki.stdout

- name: Find EBS Snapshot ID for parent image.
  shell: 'aws ec2 describe-images --region {{ ansible_ec2_placement_region }} --image-ids {{ ami_parent }} --output text | grep ^EBS'
  register: ebsparent

- name: Saving ebs_parent_id as a fact for later use
  set_fact:
    ebs_parent_id: '{{ item.split("\t")[3] }}'
  with_items: ebsparent.stdout

