---
- name: Registering HVM AMI to snapshot
  #command: 'ec2-register --name "{{ ami_name }}-HVM-EBS" --description "{{ ami_description }}" --architecture "x86_64" --root-device-name /dev/sda1 --block-device-mapping /dev/sda1={{ ebs_snapshot_id }}::true --block-device-mapping /dev/sdb=ephemeral0 --block-device-mapping /dev/sdc=ephemeral1 --block-device-mapping /dev/sdd=ephemeral2 --block-device-mapping /dev/sde=ephemeral3 --region {{ ansible_ec2_placement_region }} --virtualization-type hvm'
  command: |
    aws ec2 register-image 
      --output text
      --region {{ ansible_ec2_placement_region }}
      --name "{{ ami_name }}-HVM-EBS"
      --description "{{ ami_description }}"
      --architecture "x86_64"
      --root-device-name /dev/sda1
      --block-device-mappings
        '[{"DeviceName": "/dev/sda1","Ebs":{"SnapshotId":"{{ ebs_snapshot_id }}","DeleteOnTermination":true} },{"DeviceName":"/dev/sdb","VirtualName":"ephemeral0"},{"DeviceName":"/dev/sdc","VirtualName":"ephemeral1"},{"DeviceName":"/dev/sdd","VirtualName":"ephemeral2"},{"DeviceName":"/dev/sde","VirtualName":"ephemeral3"}]' 
  register: amihvm

- name: Saving HVM AMI ID as a fact for later use
  set_fact:
    ami_id_hvm: '{{ amihvm.stdout }}'

- name: Tagging HVM AMI
  #command: 'ec2-create-tags --region {{ ansible_ec2_placement_region }} {{ ami_id_hvm }} --tag Name="{{ ami_name }}-HVM-EBS" --tag creation_time="{{ ami_timestamp }}"'
  command: 'aws ec2 create-tags --region {{ ansible_ec2_placement_region }} --resources "{{ ami_id_hvm }}" --tags "[{\"Key\":\"Name\",\"Value\":\"{{ ami_name }}-HVM-EBS\"}, {\"Key\":\"creation_time\",\"Value\":\"{{ ami_timestamp }}\"}]"'


