---
- name: Determine IAM Role
  command: 'curl http://169.254.169.254/latest/meta-data/iam/security-credentials/'
  register: iamcheck

- name: Saving IAM Role as fact for later use
  set_fact:
    iam_role: "{{ item }}"
  with_items: iamcheck.stdout

- name: Determine IAM Role AccessKeyID 
  shell: "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/{{ buri_iam_role }} | grep AccessKeyId | sed -E 's/^.* : \"([^\"]+)\".*$/\\1/'"
  register: iam_access

- name: Saving IAM Role AccessKeyID as fact for later use
  set_fact:
    iam_access_key: "{{ iam_access.stdout }}"

- name: Determine IAM Role SecretAccessKey
  shell: "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/{{ buri_iam_role }} | grep SecretAccessKey | sed -E 's/^.* : \"([^\"]+)\".*$/\\1/'"
  register: iam_secret

- name: Saving IAM Role SecretAccessKey as fact for later use
  set_fact:
    iam_secret_key: "{{ iam_secret.stdout }}"

- name: Determine IAM Role Token
  shell: "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/{{ buri_iam_role }} | grep Token | sed -E 's/^.* : \"([^\"]+)\".*$/\\1/'"
  register: iam_token_out

- name: Saving IAM Role Token as fact for later use
  set_fact:
    iam_token: "{{ iam_token_out.stdout }}"
