---
- name: Detatch working volume for snapshotting
  command: 'aws ec2 detach-volume --region {{ ansible_ec2_placement_region }} --volume-id {{ ebs_volume_id }}'

- name: Waiting for completion of volume detatch
  command: 'aws ec2 describe-volumes --region {{ ansible_ec2_placement_region }} --volume-ids {{ ebs_volume_id }}'
  register: result
  until: result.stdout.find("ATTACHMENT") == -1
  retries: 30
  delay: 3

