---
- include: acquire_build.yml

- name: Remove any old version
  file: path={{ rssdemo_edge_app_root }}/root state=absent
  
- name: Create rssdemo_edge deployment directory
  file: path={{ rssdemo_edge_app_root }}/root state=directory

- name: Decompress rssdemo_edge WAR file
  command: chdir={{ rssdemo_edge_app_root }}/root unzip /tmp/rssdemo_edge.jar
  notify: restart rssdemo edge
  
- name: Remove source JAR file
  file: path=/tmp/rssdemo_edge.jar state=absent
  notify: restart rssdemo edge

