---
- include: acquire_build.yml

- name: Remove any old version
  file: path={{ rssdemo_edge_app_root }}/app state=absent
  
- name: Create rssdemo_edge deployment directory
  file: path={{ rssdemo_edge_app_root }}/app state=directory

- name: Decompress rssdemo_edge WAR file
  command: chdir={{ rssdemo_edge_app_root }}/app unzip /tmp/rssdemo_edge.jar
  notify: restart rssdemo edge
  
- name: Remove source JAR file
  file: path=/tmp/rssdemo_edge.jar state=absent

- name: Copy edge.properties
  template: src=edge.properties dest={{ rssdemo_edge_app_root }}/app/edge.properties owner={{ jsvc_daemon_user }} group={{ jsvc_daemon_group }} mode=0644
  notify: restart rssdemo edge

