---
- name: restart asgard
  shell: ( status jetty-instance INAME={{ asgard_instance_name }} && stop jetty-instance INAME={{ asgard_instance_name }} ) ; start jetty-instance INAME={{ asgard_instance_name }}
  when: not image_build

