---
cassandra_nameprefix: "dsc-cassandra"
cassandra_version: "1.2.16"
cassandra_mirror: "http://downloads.datastax.com/community/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_checksum: "a43e1cedadb93f784c695b659b8db265ec8055afa128a96862758bf8f4cf38f2"

cassandra_user: "cassandra"
cassandra_user: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ cassandra_nameprefix }}-{{ cassandra_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/var/log/cassandra"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"

# overridden by priam to add extension
cassandra_jvm_opts: ""

