---
cassandra_nameprefix: "apache-cassandra"
cassandra_version: "2.1.8"
#cassandra_mirror: "http://downloads.datastax.com/community/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_build_url: "http://apache.mirror.rafal.ca/cassandra/{{ cassandra_version }}/{{ cassandra_nameprefix }}-{{ cassandra_version }}-bin.tar.gz"
cassandra_checksums:
    "2.1.4": "fb5debada72905f169866ca43c21ade4782f9c036b160894e42b9072190cb7f1"
    "2.1.7":  "add1a34b8e07dacb16df6b8dbe50c66d77cb46b89f66424103e2fd4459b79089"
    "2.1.8": "3a0cc64efd529ffdc1600f6b3ad1946af85cc01544e2b469499aa81b10b722f5"
    "2.1.11": "52c863797a6e3dd57182aa7b927ee588959019fb5509c0fb10d07b28ed9f31ca"
    "2.0.14": "5396cda7a66929e9c9ea0a2eeb9f2b54327df1a42f407bc82fb1cc1648d87a1b"

cassandra_build_source: False
# this one's really slow? also a mirror
cassandra_git_repo: http://git-wip-us.apache.org/repos/asf/cassandra.git
cassandra_git_ref: cassandra-2.0

cassandra_stargate: True
cassandra_stargate_build_url: "http://downloads.tuplejump.com/stargate-core-0.9.5.tar.gz"
cassandra_stargate_checksum: "fb15882eedab70907bdc1e97c2e520cc4c9d368fc0e45d4e49f43a7e0aaba868"
cassandra_stargate_build_source: True
cassandra_stargate_git_repo: https://github.com/tuplejump/stargate-core.git
cassandra_stargate_git_ref: develop

cassandra_user: "cassandra"
cassandra_group: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ cassandra_nameprefix }}-{{ cassandra_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/var/log/cassandra"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"

cassandra_partitioner: "org.apache.cassandra.dht.RandomPartitioner"
cassandra_stream_throughput: 400
cassandra_index_interval: 256

# Thrift RPC settings:
cassandra_rpc_enable: "True"
cassandra_rpc_min_threads: 4
cassandra_rpc_max_threads: 16
cassandra_rpc_frame_size: 15
cassandra_rpc_server_type: "hsha"

# overridden by priam to add extension
cassandra_jvm_opts: ""

cassandra_enable_riemann_report: True
cassandra_riemann_seconds: 1
cassandra_riemann_tags:
  - 'cassandra'
  - "{{ buri_cluster_name }}"

riemann_extra_tags:
  - cassandra
