---
exhibitor_instance_port: 8401
exhibitor_instance_jmx_port: 7401
exhibitor_jvm_xmx: '512m'
exhibitor_cluster_name: 'default'
exhibitor_s3_bucket: 'exhibitor'
exhibitor_opts_configtype: 's3'
exhibitor_opts_s3region: 'us-east-1' # i.e. us-east-1
# If true, the Explorer UI will allow nodes to be modified (use with caution).
exhibitor_opts_nodemodification: "false" # true/false
# If true, enables AWS S3 backup of ZooKeeper log files (s3credentials may be provided as well).
exhibitor_opts_s3backup: True
# From here and above, environmental aspects, see envronment configs for better examples
# Below, internal role attributes

# required for any jetty9_instance
exhibitor_instance_name: exhibitor
exhibitor_jvm_extra_opts: -Darchaius.deployment.applicationId=exhibitor -Dexhibitor-hostname=$([ -e /usr/bin/ec2metadata ] && ec2metadata --public-hostname || hostname)
exhibitor_webapps_root: "{{ jetty_apps }}/{{ exhibitor_instance_name }}/webapps"


zookeeper_version: '3.4.5'
zookeeper_basename: 'zookeeper-{{ zookeeper_version }}'
zookeeper_mirror: 'http://mirrors.ibiblio.org/apache/zookeeper/{{ zookeeper_basename }}/{{ zookeeper_basename }}.tar.gz'
zookeeper_checksum: 'e92b634e99db0414c6642f6014506cc22eefbea42cc912b57d7d0527fb7db132'
zookeeper_install_dir: '/opt/zookeeper'

exhibitor_version: '1.5.1'
exhibitor_basename: 'exhibitor-{{ exhibitor_version }}'
exhibitor_build_url: 'http://slash-etc.com/java/{{ exhibitor_basename }}.war'
exhibitor_checksum: 'bf58be69f440cb3ab3bfb4ee0b622c87f55d0fe9f8f2f5bbb74d4a06db6d7893'

# New git-based building controls
exhibitor_build_source: False
exhibitor_git_repo: https://github.com/Netflix/exhibitor.git
exhibitor_git_ref: master

exhibitor_script_dir: '/usr/local/bin/'
exhibitor_snapshot_dir: '/mnt/zookeeper/snapshot'
exhibitor_transaction_dir: '/mnt/zookeeper/transactions'
exhibitor_log_index_dir: '/mnt/zookeeper/log_indexes'
exhibitor_check_script: '{{ exhibitor_script_dir }}/check-local-zk.py'
exhibitor_log4j_props: '{{ exhibitor_webapps_root }}/root/WEB-INF/classes/log4j.properties'
exhibitor_loglevel: 'info'
# For --configtype s3, backups
exhibitor_s3key: ''
exhibitor_s3secret: ''
exhibitor_opts_defaultconfig: '{{ exhibitor_webapps_root }}/root/WEB-INF/classes/exhibitor.properties'
# For --contigtype file
exhibitor_opts_fsconfigdir: '/tmp'
# For --configtype s3, set:
exhibitor_opts_s3config: '{{ exhibitor_s3_bucket }}:{{ exhibitor_cluster_name }}-config'
# Max lines of logging to keep in memory for display.
exhibitor_opts_loglines: "1000"
# If enabled, ZooKeeper will be queried once a minute for its state via the 'mntr' four letter word
# (this requires ZooKeeper 3.4.x+). Servo will be used to publish this data via JMX.
exhibitor_opts_servo: "true"
# Connection timeout (ms) for ZK connections.
exhibitor_opts_timeout: "30000"
# Period (ms) to check for shared config updates.
exhibitor_opts_configcheckms: 30000
# Styling used for the JQuery-based UI. Currently available options: red, black, custom
exhibitor_opts_jquerystyle: "red"
# Extra text to display in UI header
exhibitor_opts_headingtext: "Exhibitor - {{ exhibitor_cluster_name }}"
exhibitor_defaultconfig_cleanup_period_ms: '300000'
exhibitor_defaultconfig_zookeeper_install_directory: '{{ zookeeper_install_dir }}/*'
exhibitor_defaultconfig_check_ms: '30000'
exhibitor_defaultconfig_backup_period_ms: '0'
exhibitor_defaultconfig_client_port: '2181'
exhibitor_defaultconfig_cleanup_max_files: '20'
exhibitor_defaultconfig_backup_max_store_ms: '0'
exhibitor_defaultconfig_connect_port: '2888'
exhibitor_defaultconfig_backup_extra: ''
exhibitor_defaultconfig_observer_threshold: '0'
exhibitor_defaultconfig_election_port: '3888'
exhibitor_defaultconfig_zoo_cfg_extra: 'tickTime\=2000&initLimit\=10&syncLimit\=5'
exhibitor_defaultconfig_auto_manage_instances_settling_period_ms: '0'
exhibitor_defaultconfig_auto_manage_instances: '1'
exhibitor_defaultconfig_servers_spec: ''

# For multiple clusters, apply cluster name
ami_suffix: "{{ exhibitor_cluster_name }}"
