---
zookeeper_version: '3.4.5'
zookeeper_basename: 'zookeeper-{{ zookeeper_version }}'
zookeeper_mirror: 'http://mirrors.ibiblio.org/apache/zookeeper/{{ zookeeper_basename }}/{{ zookeeper_basename }}.tar.gz'
zookeeper_checksum: 'e92b634e99db0414c6642f6014506cc22eefbea42cc912b57d7d0527fb7db132'
zookeeper_install_dir: '/opt/zookeeper'
zookeeper_user: 'zookeeper'
zookeeper_group: 'zookeeper'
exhibitor_version: '1.5.1'
exhibitor_basename: 'exhibitor-{{ exhibitor_version }}'
exhibitor_mirror: 'http://slash-etc.com/java/{{ exhibitor_basename }}.jar'
exhibitor_checksum: '21b08ec5a2debc16ec3948b3f334b9decf537828bcfb139133681eb25eece01e'
exhibitor_install_dir: '/opt/exhibitor'
exhibitor_script_dir: '/usr/local/bin/'
exhibitor_snapshot_dir: '/tmp/zookeeper'
exhibitor_transaction_dir: '/mnt/zookeeper'
exhibitor_log_index_dir: '/tmp/zookeeper_log_indexes'
exhibitor_check_script: '{{ exhibitor_script_dir }}/check-local-zk.py'
exhibitor_jar_dest: '{{ exhibitor_install_dir }}/{{ exhibitor_version }}.jar'
exhibitor_log4j_props: '{{ exhibitor_install_dir }}/log4j.properties'
exhibitor_log_to_syslog: '1'
exhibitor_loglevel: 'info'
# For --configtype s3, backups
exhibitor_s3key: ''
exhibitor_s3secret: ''
exhibitor_opts_port: '8080'
exhibitor_opts_defaultconfig: '{{ exhibitor_install_dir }}/exhibitor.properties'
exhibitor_opts_s3credentials: '{{ exhibitor_install_dir }}/exhibitor.s3.properties'
exhibitor_opts_configtype: 's3'
# For --contiftype file
exhibitor_opts_fsconfigdir: '/tmp'
# For --configtype s3, set:
exhibitor_opts_s3config: 'exhibitor:exhibitor-config'
exhibitor_opts_s3region: 'us-east-1' # i.e. us-east-1
# If true, enables AWS S3 backup of ZooKeeper log files (s3credentials may be provided as well).
exhibitor_opts_s3backup: True
# Max lines of logging to keep in memory for display.
exhibitor_opts_loglines: "1000"
# If true, the Explorer UI will allow nodes to be modified (use with caution).
exhibitor_opts_nodemodification: "false" # true/false
# If enabled, ZooKeeper will be queried once a minute for its state via the 'mntr' four letter word
# (this requires ZooKeeper 3.4.x+). Servo will be used to publish this data via JMX.
exhibitor_opts_servo: "true"
# Connection timeout (ms) for ZK connections.
exhibitor_opts_timeout: "30000"
# Period (ms) to check for shared config updates.
exhibitor_opts_configcheckms: 30000
# Styling used for the JQuery-based UI. Currently available options: red, black, custom
exhibitor_opts_jquerystyle: "red"
# Extra text to display in UI header
exhibitor_opts_headingtext: "Exhibitor"
exhibitor_defaultconfig_cleanup_period_ms: '300000'
exhibitor_defaultconfig_zookeeper_install_directory: '{{ zookeeper_install_dir }}/*'
exhibitor_defaultconfig_check_ms: '30000'
exhibitor_defaultconfig_backup_period_ms: '0'
exhibitor_defaultconfig_client_port: '2181'
exhibitor_defaultconfig_cleanup_max_files: '20'
exhibitor_defaultconfig_backup_max_store_ms: '0'
exhibitor_defaultconfig_connect_port: '2888'
exhibitor_defaultconfig_backup_extra: ''
exhibitor_defaultconfig_observer_threshold: '0'
exhibitor_defaultconfig_election_port: '3888'
exhibitor_defaultconfig_zoo_cfg_extra: 'tickTime\=2000&initLimit\=10&syncLimit\=5'
exhibitor_defaultconfig_auto_manage_instances_settling_period_ms: '0'
exhibitor_defaultconfig_auto_manage_instances: '1'
exhibitor_defaultconfig_servers_spec: ''

