---
# Ice role
- name: Copy tomcat server.xml file
  copy: src=server.xml dest=/usr/local/tomcat/conf/server.xml owner=root group=root mode=0644
  notify: restart tomcat
  tags: deploy

- name: Remove default root webapp
  file: path=/usr/local/tomcat/webapps/ROOT state=absent
  notify: restart tomcat
  tags: deploy

- name: Download snapshot build of Ice from Cloudbees
  get_url: url={{ ice_build_url }} dest=/usr/local/tomcat/webapps/ice.war
  tags: deploy
  
- name: Remove any old version
  file: path=/usr/local/tomcat/webapps/ice state=absent
  tags: deploy
  
- name: Create Ice deployment directory
  file: path=/usr/local/tomcat/webapps/ice state=directory
  tags: deploy

- name: Decompress Ice WAR file
  command: chdir=/usr/local/tomcat/webapps/ice unzip ../ice.war
  notify: restart tomcat
  tags: deploy
  
- name: Remove source WAR file
  file: path=/usr/local/tomcat/webapps/ice.war state=absent
  notify: restart tomcat
  tags: deploy

- name: Copy ice.properties
  template: src=ice.properties.j2 dest=/usr/local/tomcat/webapps/ice/WEB-INF/classes/ice.properties owner=root group=root mode=0644
  notify: restart tomcat
  tags: config
  
- name: Add ICE_HOME to environment (apt version)
  lineinfile: dest=/etc/default/tomcat7 regexp="ICE_HOME" line="ICE_HOME=/usr/local/tomcat/webapps/ice/WEB-INF/classes/"
  when: ansible_distribution == 'Ubuntu'
  notify: restart tomcat
  tags: config

- name: Adding ephemeral_dirs spec for ice
  template: src=ephemeral_dirs dest=/etc/ephemeral_dirs owner=root group=root mode=0644
  tags: config
   
