---
# Ice role
- name: Copy jetty app context xml file
  copy: src=ice.xml dest={{ ice_webapps_root }}/ice.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Copy jetty realm.properties file
  template: src=realm.properties dest={{ jetty_apps }}/{{ ice_instance_name }}/etc/ owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Remove default root webapp
  file: path={{ ice_webapps_root }}/ROOT state=absent
  notify: restart webapps container

- name: Download snapshot build of Ice from Cloudbees
  get_url: url={{ ice_build_url }} dest=/tmp/ice.war
  
- name: Remove any old version
  file: path={{ ice_webapps_root }}/ice state=absent
  
- name: Create Ice deployment directory
  file: path={{ ice_webapps_root }}/ice state=directory

- name: Decompress Ice WAR file
  command: chdir={{ ice_webapps_root }}/ice unzip /tmp/ice.war
  notify: restart webapps container
  
- name: Remove source WAR file
  file: path=/tmp/ice.war state=absent
  notify: restart webapps container

- name: Copy ice.properties
  template: src=ice.properties.j2 dest={{ ice_webapps_root }}/ice/WEB-INF/classes/ice.properties owner=root group=root mode=0644
  notify: restart webapps container
  
- name: Add ICE_HOME to environment
  lineinfile: dest=/etc/default/jetty regexp="ICE_HOME" line="ICE_HOME={{ ice_webapps_root }}/ice/WEB-INF/classes/"
  when: ansible_distribution == 'Ubuntu' and servlet_container == "jetty9"
  notify: restart webapps container

- name: Add BASIC auth requirements to web.xml
  lineinfile: dest={{ ice_webapps_root }}/ice/WEB-INF/web.xml regexp="security-constraint" line="<security-constraint><web-resource-collection><web-resource-name></web-resource-name><url-pattern>/*</url-pattern></web-resource-collection><auth-constraint><role-name>ice</role-name></auth-constraint></security-constraint><login-config><auth-method>BASIC</auth-method><realm-name>ice</realm-name></login-config>" insertbefore="</web-app>"
  notify: restart webapps container


- name: Adding ephemeral_dirs spec for ice
  template: src=ephemeral-dirs dest=/etc/ephemeral-dirs owner=root group=root mode=0644
   
