---
jetty_version: '9.2.10.v20150310'
jetty_basename: 'jetty-distribution-{{ jetty_version }}'
jetty_filename: '{{ jetty_basename }}.tar.gz'
jetty_mirror: 'http://eclipse.mirror.rafal.ca/jetty/{{ jetty_version }}/dist/{{ jetty_filename }}'
jetty_checksum: '0034587a3dcfdab23fca28291e5e22ae7ff6e80f9f4c7a67f5b2b7777a84b40e'
jetty_root: '/opt/jetty'
jetty_temp: '{{ jetty_root }}/temp'
jetty_apps: '{{ jetty_root }}/apps'
jetty_install_dir: '{{ jetty_root }}/{{ jetty_basename }}'
jetty_user: 'jetty'
jetty_group: 'jetty'
# Used as generics for container user elsewhere, and switching behavior based on containers
servlet_container: 'jetty9'
servlet_container_user: '{{ jetty_user }}'
servlet_container_group: '{{ jetty_group }}'
