---
- name: Registering cross-account permission for HVM AMI
  command: aws ec2 modify-image-attribute --region us-east-1 --image-id '{{ perm_ami_id }}' --launch-permission "{\"Add\":[{\"UserId\":\"{{ item.value.account }}\"}]}"
  with_dict: {{ ami_cross_account }}
  when: ami_cross_account is defined
