---
ice_build_url: https://netflixoss.ci.cloudbees.com/job/ice-master/lastSuccessfulBuild/artifact/target/ice.war

# The S3 buckets and prefixes (comma separated) where your S3 programmatic
# billing files are stored
ice_billing_s3_bucket_names: example-billing
ice_billing_s3_bucket_prefix: 

# Your company's name
ice_company_name: Your Company Name

# The S3 bucket Ice can use as it's workspace (needs read and write access)
ice_work_s3_bucket_name: example-ice-work

ice_admin_password: "blah"

# change the follow account settings in your site.yml w/ an override
# At least one account with it's account_no set is required. The
# rest is optional for more complex setups
ice_accounts:
  # label used to reference account in UI and elsewhere
  - production:
    # account number in question
    - account_no: 123456789
    - owner_accounts:
      - staging
      - test
    # if reservation capacity poller needs to use IAM role to access ec2 API, set the assumed role here for each reservation owner account
    - owner_role: Ice
    # if reservation capacity poller needs to use IAM role to access ec2 API and external id is used, set the external id here for each reservation owner account. otherwise you can leave it unset.
    #- owner_ext_id: 
  # Repeat for all your accounts
  - staging:
    - account_no: 123456789
    - owner_accounts:
      - production
      - test
    - owner_role: Ice
    #- owner_ext_id: bar
  - test:
    - account_no: 123456789
    - owner_accounts:
      - production
      - staging
    - owner_role: foo
    #- owner_ext_id: bar

