---
# Main task list for Base

- include: harden-basic.yml
- include: package-install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include: install-other.yml
- include: setup-services.yml
- include: monitoring-clodwatch.yml
  when: cloud_target == 'amazon'
