---
- name: Copy jetty app context xml file
  copy: src=turbine.xml dest={{ turbine_webapps_root }}/turbine.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart turbine
  when: servlet_container == "jetty9"

- include: acquire_build.yml

- name: Remove any old version
  file: path={{ turbine_webapps_root }}/turbine state=absent
  
- name: Create turbine deployment directory
  file: path={{ turbine_webapps_root }}/turbine state=directory

- name: Decompress turbine WAR file
  command: chdir={{ turbine_webapps_root }}/turbine unzip /tmp/turbine.war
  notify: restart turbine
  
- name: Remove source WAR file
  file: path=/tmp/turbine.war state=absent
  notify: restart turbine

- name: Copy turbine.properties
  template: src=config.properties dest={{ turbine_webapps_root }}/turbine/WEB-INF/classes/config.properties owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0644
  notify: restart turbine

