---
priam_cass_nameprefix: "dsc-cassandra"
priam_cass_version: "1.2.10"
priam_cass_mirror: "http://downloads.datastax.com/community/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}-bin.tar.gz"
priam_cass_checksum: "c731c8e2bc84769f884f423fb839ab3205279972b842ab37fdace49ef511e544"
priam_version: "1.2.17"
priam_mirror: "http://dl.imedidata.net/cassandra/priam/{{ priam_version }}/priam-web-{{ priam_version }}.war"
priam_checksum: "fbc1779f9cff9a8e3a4933000a9f2784c2037519f0e1f2777ae39dfee9d831a0"
priam_ext_mirror: "http://dl.imedidata.net/cassandra/priam/{{ priam_version }}/priam-cass-extensions-{{ priam_version }}.jar"
priam_ext_checksum: "f5cbee81dd885d07c5e3aff9b45de5a8cf9674eecc4a8af0bcd736a9c86afdab"

cassandra_user: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/mnt/cassandra/logs"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"
priam_cass_startscript: "service cassandra start"
priam_cass_stopscript: "service cassandra stop"
priam_upload_throttle: "5"

# priam_clustername MUST match the autoscaling group name (before the dash) in order to be used 
# i.e. project_stage_db-useast1 == cluster_name-ec2region
# priam_clustername is effectively the reference to the correct set of SimpleDB Configuration
priam_clustername: "priam"
priam_multiregion_enable: false
priam_endpoint_snitch: "org.apache.cassandra.locator.Ec2Snitch"

# This must be set for all multiregion and any single region deployments outside the first three (abc) AZs/datacenters in a region
# i.e. "us-east-1a,us-east-1c,us-west-1a,us-west-1b,us-west-1c" or "us-east-1c,us-east-1d"
# If not set it will not be applied
priam_zones_available: ""

# If you want backups, set this variable to the name of an s3 bucket you have created.
priam_s3_bucket: "SET_ME_PLEASE"
priam_s3_base_dir: "cassandra_backups"



