---
priam_cass_nameprefix: "dsc-cassandra"
priam_cass_version: "1.2.16"
priam_cass_mirror: "http://downloads.datastax.com/community/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}-bin.tar.gz"
priam_cass_checksum: "a43e1cedadb93f784c695b659b8db265ec8055afa128a96862758bf8f4cf38f2"
priam_version: "1.2.30"
priam_mirror: "http://slash-etc.com/java/priam-web-{{ priam_version }}.war"
priam_checksum: "d35cace79ca676cb3a8b72175c414a0bdbfd58192a965e18a373f870825e54e6"
priam_ext_mirror: "http://slash-etc.com/java/priam-cass-extensions-{{ priam_version }}.jar"
priam_ext_checksum: "730deace3fc80ee2c06c587ca6af3c46cc734f9fdfacf2b1eb5d47e7668553f3"

cassandra_user: "cassandra"
cassandra_home: "/opt/cassandra"
cassandra_installdir: "/opt/{{ priam_cass_nameprefix }}-{{ priam_cass_version }}"
cassandra_base_location: "/mnt/cassandra"
cassandra_log_location: "/mnt/cassandra/logs"
cassandra_data_location: "/mnt/cassandra/data"
cassandra_cache_location: "/mnt/cassandra/saved_caches"
cassandra_commitlog_location: "/mnt/cassandra/commitlog"
priam_cass_startscript: "service cassandra start"
priam_cass_stopscript: "service cassandra stop"
priam_upload_throttle: "5"

priam_backup_hour: "4"
# The recommended Value is 16 to 32 times the rate of write throughput (in MB/s)
priam_compaction_throughput: 0
# The recommended value is 5 to 10 percent of the available Java heap size
priam_compaction_limit: 256

# priam_clustername MUST match the autoscaling group name (before the dash) in order to be used 
# i.e. project_stage_db-useast1 == cluster_name-ec2region
# priam_clustername is effectively the reference to the correct set of SimpleDB Configuration
priam_clustername: "priam"
priam_multiregion_enable: false
priam_acl_groupname: ""
# It is not advised to change this, even if not multi-region
# See: https://github.com/Netflix/Priam/wiki/Properties#snitch-selection
priam_endpoint_snitch: "org.apache.cassandra.locator.Ec2MultiregionSnitch"

# This must be set for all multiregion and any single region deployments outside the first three (abc) AZs/datacenters in a region
# i.e. "us-east-1a,us-east-1c,us-west-1a,us-west-1b,us-west-1c" or "us-east-1c,us-east-1d"
# If not set it will not be applied
priam_zones_available: ""

# If you want backups, set this variable to the name of an s3 bucket you have created.
priam_s3_bucket: "SET_ME_PLEASE"
priam_s3_base_dir: "cassandra_backups"



