---
priam_instance_port: 8080
priam_instance_jmx_port: 1099
priam_jvm_xmx: '1024m'
priam_backup_hour: "4"
# The recommended Value is 16 to 32 times the rate of write throughput (in MB/s)
# This is a throttle, 0 means do not throttle
# NOT USED in C* 2.1
priam_compaction_throughput: 0

# The recommended value is 5 to 10 percent of the available Java heap size
priam_compaction_limit: 256
# Disable if you like, not used in classic NetflixOSS setups
priam_native_transport_enabled: true
# Name of cluster instance (for supporting multiple clusters)
priam_cluster_name: "{{ buri_cluster_name|default('default') }}"
# Set this true unless in a VPC in a single region
priam_multiregion_enable: true
# How Priam reports cluster member to eachother changes in a VPC, this is the signal to do so
priam_vpc: false
priam_internode_encryption: "dc"
# It is not advised to change this, even if not multi-region
# See: https://github.com/Netflix/Priam/wiki/Properties#snitch-selection
# However, if in a VPC, single region, set to Ec2Snitch
priam_endpoint_snitch: "org.apache.cassandra.locator.Ec2MultiRegionSnitch"
# This must be set for all multiregion and any single region deployments outside the first three (abc) AZs/datacenters in a region
# i.e. "us-east-1a,us-east-1c,us-west-1a,us-west-1b,us-west-1c" or "us-east-1c,us-east-1d"
# If not set it will not be applied
priam_zones_available: ""
# If you want backups, set this variable to the name of an s3 bucket you have created.
priam_s3_bucket: "SET_ME_PLEASE"
# This is in BYTES per second, and is the rate at which backups to S3 will limit network use
priam_upload_throttle: "5242880"
# From here and above, environmental aspects, see envronment configs for better examples
# Below, internal role attributes

# required for any jetty9_instance
priam_instance_name: priam
priam_jvm_extra_opts: -Darchaius.deployment.applicationId=priam
priam_webapps_root: "{{ jetty_apps }}/{{ priam_instance_name }}/webapps"

priam_version: "1.2.30"
priam_mirror: "http://slash-etc.com/java/priam-web-{{ priam_version }}.war"
priam_checksum: "829cbb67746364566de57fc31605992dcc230e545f28a47e910ccff24b9f4dca"
priam_ext_mirror: "http://slash-etc.com/java/priam-cass-extensions-{{ priam_version }}.jar"
priam_ext_checksum: "2c845fd10d957ef631e87a6944b9009174dea2d69b948552280267b754a3182d"

priam_build_source: True
priam_git_repo: https://github.com/jhohertz/Priam.git
priam_git_ref: staging_2.0

priam_cass_startscript: "/etc/init.d/cassandra start"
priam_cass_stopscript: "/etc/init.d/cassandra stop"

# You *can* override these, but better to use a convention here
# priam_cluster_name MUST match the autoscaling group name (before the dash) in order to be used 
# i.e. project_stage_db-useast1 == cluster_name-ec2region
# priam_cluster_name is effectively the reference to the correct set of SimpleDB Configuration
priam_acl_groupname: "priam-{{ priam_cluster_name }}"
priam_s3_base_dir: "{{ priam_cluster_name }}_backups"
priam_populate_sdb: False
