---
# Set "full" name to be used in tagging. Other process may append additional details (IE: -ebs or -s3)

# New way, looks to the hostvars for what the chroot host set as facts for the build
- name: Setting AMI appversion information
  set_fact:
    buri_ami_appversion: "{{ buri_ami_base_name }}-{{ hostvars[buri_ami_mount_point]['buri_build_version']|default('unavailable') }}-{{ hostvars[buri_ami_mount_point]['buri_build_release']|default(buri_ami_release_timestamp) }}"

- name: Setting AMI full build name (less machine/disk suffixes)
  set_fact:
    buri_ami_full_name: "{{ buri_ami_appversion }}-x86_64-{{ buri_ami_suffix|default(buri_ami_release_timestamp) }}"

- name: Setting AMI description
  set_fact:
    buri_ami_description: "name={{ buri_ami_base_name }}, arch=x86_64, ancestor_name={{ buri_ami_ancestor_name|default('') }}, ancestor_id={{ buri_ami_ancestor_id|default('') }}, ancestor_version={{ buri_ami_ancestor_version|default('') }}"

