---
dependencies:
  - { role: jetty9, jetty_port: '{{ priam_port }}' }
  - { role: cassandra, cassandra_user: '{{ servlet_container_user }}', cassandra_group: '{{ servlet_container_group }}', cassandra_jvm_opts: '-javaagent:${CASSANDRA_HOME}/lib/priam-cass-extensions-{{ priam_version }}.jar' }
