---
- name: Provisioning role against chroot
  hosts: chroots
  connection: chroot
  user: root
  sudo: True
  vars_files:
    - [ "{{ buri_environment }}/local/overrides.yml", "vars/dummy.yml" ]
  vars:
    image_build: true
  roles:
    - "{{ ami_role }}"
