---
- name: Provisioning role against chroot
  hosts: chroots
  connection: chroot
  user: root
  sudo: True
  vars:
    image_build: true
    cloud_target: amazon
  tasks:
    - name: Record Buri cluster name
      copy: dest=/tmp/buri_cluster_name content={{ buri_cluster_name }} owner=root group=root mode=0644
      when: buri_cluster_name is defined and buri_cluster_name != ''
  roles:
    - "{{ buri_role }}"
