---
- name: Adding host to inventory
  hosts: localhost
  connection: local
  vars:
    image_build: false
    cloud_target: vm
  tasks:
    - name: Register host target in ansible inventory
      add_host: hostname={{ machine_target }} groups=anshost

- name: Provisioning role against host
  hosts: anshost
  user: dev
  sudo: True
  vars:
    image_build: false
    cloud_target: vm
  vars_files:
    - [ "{{ buri_environment }}/local/overrides.yml" ]
  roles:
    - cassandra
    - exhibitor
    - eureka
    - hystrix_dashboard
    - turbine
    - graphite
    - fluxdemo_edge
    - fluxdemo_middle
