- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  vars:
    #ami_role: destroy_ebs
  vars_files:
    - [ "{{ buri_environment }}/local/overrides.yml" ]
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/detach_failed_vol.yml

