- name: Disconnect, snapshot, and register newly formed AMI
  hosts: localhost
  connection: local
  sudo: True
  tags: resnap
  vars:
    #ami_role: destroy_ebs
  vars_files:
    - vars/ami.yml
    - [ "local/site.yml", "vars/site.defaults.yml" ]
  tasks:
    - include: tasks/ec2_get_facts.yml
    - include: tasks/detach_failed_vol.yml

