---
# Playbook to create a foundation snapshot/AMI from ubuntu's source images
- name: Mounting EBS snapshot to work from
  hosts: localhost
  connection: local
  sudo: True
  #vars:
  vars_files:
    - vars/ami.yml
    - roles/{{ ami_role }}/defaults/main.yml
    - [ "local/site.yml", "vars/site.defaults.yml" ]
  tasks:
    - include: tasks/set_build_info.yml
    - include: tasks/ec2_get_facts.yml
    - include: tasks/ec2_get_iam_info.yml
    - include: tasks/ec2_ami_lookup.yml
    - include: tasks/ec2_create_vol_and_attach.yml
    - include: tasks/filesystem-grow.yml
      when: ami_root_resize
    - include: tasks/chroot_mount_and_setup.yml
    - name: Register chroot target in ansible inventory
      add_host: hostname={{ ami_image_mount }} groupname=chroots

- include: _image_apply_role.yml
- include: _image_finalize.yml

