---
- name: Adding host to inventory
  hosts: localhost
  connection: local
  vars_files:
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars:
    image_build: false
  tasks:
    - name: Register host target in ansible inventory
      add_host: hostname={{ machine_target }} groups={{ ami_role }},anshost

- name: Provisioning role against host
  hosts: anshost
  user: dev
  sudo: True
  vars_files:
    - [ "{{ BURI_BASE }}/local/env/{{ buri_environment }}/overrides.yml", "vars/dummy.yml" ]
  vars: 
    image_build: false
  roles:
    - '{{ ami_role }}'
