---
- name: Adding host to inventory
  hosts: localhost
  connection: local
  vars_files:
    - [ "{{ buri_environment }}/local/overrides.yml" ]
  tasks:
    - name: Register host target in ansible inventory
      add_host: hostname={{ machine_target }} groups=anshost

- name: Provisioning role against host
  hosts: anshost
  user: dev
  sudo: True
  vars_files:
    - [ "local/site.yml", "vars/site.defaults.yml" ]
  vars: 
    image_build: false
  roles:
    - '{{ ami_role }}'
