---
# Exhibitor role
- name: Create zookeeper install directory
  file: path={{ zookeeper_install_dir }} state=directory owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0755

- name: Download zookeeper release archive
  get_url: url={{ zookeeper_mirror }} dest=/tmp/{{ zookeeper_basename }}.tar.gz sha256sum={{ zookeeper_checksum }} owner=root mode=0644

- name: Extract zookeeper release archive to install dir
  command: tar -C {{ zookeeper_install_dir }} -zxf /tmp/{{ zookeeper_basename }}.tar.gz

- name: Set ownership of installed release archive
  file: path={{ zookeeper_install_dir }}/{{ zookeeper_basename }} state=directory recurse=yes owner={{ servlet_container_user }} group={{ servlet_container_group }}

- name: Download Exhibitor release WAR
  get_url: url={{ exhibitor_mirror }} dest=/tmp/exhibitor.war sha256sum={{ exhibitor_checksum }} owner=root mode=0644
  
- name: Remove any old version
  file: path={{ webapps_root }}/root state=absent
  
- name: Create Exhibitor deployment directory
  file: path={{ webapps_root }}/root state=directory

- name: Decompress Exhibitor WAR file
  command: chdir={{ webapps_root }}/root unzip /tmp/exhibitor.war
  notify: restart webapps container
  
- name: Remove source WAR file
  file: path=/tmp/exhibitor.war state=absent

- name: Install Exhibitor S3 access key information to property file.
  template: src=exhibitor.s3.properties dest={{ exhibitor_opts_s3credentials }} owner={{ servlet_container_user }} mode=0440
  when: exhibitor_s3key != '' and exhibitor_s3secret != ''

- name: Install Exhibitor logging properties.
  template: src=log4j.properties dest={{ exhibitor_log4j_props }} owner=root group=root mode=0644

- name: Install local zookeeper check script.
  template: src=check-local-zk.py dest={{ exhibitor_check_script }} owner={{ servlet_container_user }} mode=0744

- name: Install Exhibitor default property file.
  template: src=exhibitor.properties dest={{ exhibitor_opts_defaultconfig }} owner={{ servlet_container_user }} mode=0644

- name: Copy jetty app context xml file
  copy: src=exhibitor.xml dest={{ webapps_root }}/root.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart webapps container
  when: servlet_container == "jetty9"

- name: Add ephemeral mkdir spec for exhibitor role
  template: src=ephemeral-dirs dest=/etc owner=root mode=0644














